# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a3940c4173ecdc7e083a0e4722d9876842ada5b13a5d95679ac01b5909d6a2254d78f0bcbea476462d006bbb45df073aaa5704ddd5652c4bf0c9313f42d6ca4

test:
  secret_key_base: 7cae410c58f1eb65ca19fac7cd707fe0248f29fb15fbc2c043f74ff16553a6399505fc7160230b7bd73d4da51764f319637c8d89b24c16c49c5cab8790635912

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
